env: "local"

http_server: 
  host: "localhost"
  timeout: 4s
  port: 8000
  idle_timeout: 60s
  read_timeout: 10s
  write_timeout: 10s
  jwt_secret: super_secret_key
  secure_cookies: false
db: 
  host: "localhost"
  port: "3306"
  username: "default"
  password: "Qwerty12345"
  dbname: "pastebin"
  sslmode: "disable"