env: "local"

http_server: 
  host: "localhost"
  timeout: 4s
  port: 8000
  idle_timeout: 60s

db: 
  host: "localhost"
  port: "3306"
  username: "default"
  password: "default"
  dbname: "pastebin"
  sslmode: "disable"