env: "local"

http_server: 
  host: "localhost"
  timeout: 4s
  port: 8000
  idle_timeout: 60s
  read_timeout: 10s
  write_timeout: 10s
  jwt_secret: super_secret_key
  secure_cookies: false
db: 
  host: "localhost"
  port: "3306"
  username: "default"
  password: "Qwerty12345"
  dbname: "pastebin"
  sslmode: "disable"
s3:
  endpoint: "https://pupuha-dev.object.pscloud.io"
  bucket: "pupuha-dev"
  access_key: "V9M58P398E715KZHYNPS"
  secret_key: "IO24QaIQ1i0xROcnKF2fwO77CyI7E0TXmFs88ffq"
#  use_ssl: false
  region: "us-east-1"
redis:
  host: "redis"
  port: "6379"
  password: "Qwerty12345"