services:
  postgres:
    image: postgres:16
    container_name: pastebin-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"

  redis:
    image: redis:7
    container_name: pastebin-redis
    ports:
      - "6379:6379"